version: '3'
services:
  ipfs-public:
    image: node:10
    volumes:
      - ./app:/opt/app
      - ./entry.sh:/opt/app/entry.sh
      - ./repos_ipfs_public:/opt/app/repos_ipfs_public
      - ./cnwiki:/opt/app/cnwiki
    working_dir: "/opt/app"
    command: ./entry.sh
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M
networks:
  outside:
    external:
      name: "host"
