version: '3'
services:
  ipfs-save:
    image: node:10
    volumes:
      - ./app:/opt/app
      - ./ipfs-cnwiki.js:/opt/app/ipfs-cnwiki.js
      - ./ipfs-main.js:/opt/app/ipfs-main.js
      - ./ipfs-save.js:/opt/app/ipfs-save.js
      - ./parseWikiDumper.js:/opt/app/parseWikiDumper.js
      - ./repos_ipfs_public:/opt/app/repos_ipfs_public
      - ./cnwiki:/opt/app/cnwiki
      - /watorvapor/wai.storage/dumps.wikimedia.org/zhwiki:/watorvapor/wai.storage/dumps.wikimedia.org/zhwiki
    working_dir: "/opt/app"
    command: ./entry.sh
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M
networks:
  outside:
    external:
      name: "host"
