version: '3'
services:
  wiktionary-ja:
    image: node
    volumes:
      - ./:/wiktionary
      - /watorvapor/wai.storage/wiktionary/input_db:/input
      - /watorvapor/wai.storage/wiktionary/out_db:/out
    working_dir: "/wiktionary"
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: 128M
        reservations:
          cpus: '0.60'
          memory: 32M
    command: node dict_ja.js
networks:
  outside:
    external:
      name: "host"
      
