version: '3'
services:
  ipfs-crawler:
    image: node
    volumes:
      - ./:/crawler_app
    working_dir: "/crawler_app"
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '3.00'
          memory: 128M
        reservations:
          cpus: '1.0'
          memory: 64M
    command: node app.js
    restart: always


networks:
  outside:
    external:
      name: "host"
