version: '3'
services:
  ipfs-crawler:
    image: node
    volumes:
      - ./:/crawler_app
    working_dir: "/crawler_app"
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 128M
        reservations:
          cpus: '0.50'
          memory: 64M
    command: node app.js
    restart: always
