version: '3'
services:
  ipfs-public:
    image: ipfs/go-ipfs:release
    volumes:
      - ./export:/export
      - ./storage:/data/ipfs
    command: daemon
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '2.50'
          memory: 3G
        reservations:
          cpus: '0.1'
          memory: 256M
networks:
  outside:
    external:
      name: "host"
