version: '3'
services:
  conv:
    image: node:lts
    volumes:
      - ./:/opt/app
      - /watorvapor/wai.storage/hashArchive:/watorvapor/wai.storage/hashArchive
      - /watorvapor/wai.storage/old.hashArchive:/watorvapor/wai.storage/old.hashArchive
    working_dir: "/opt/app"
    command: node conv_sha1_2_hash.js
    networks:
      - outside
    deploy:
      resources:
        limits:
          cpus: '3.00'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M
networks:
  outside:
    external:
      name: "host"
